#! /usr/bin/python
# SniffyDB is a CS 411 Project 
# by Shane Rogers, Simon Kim, Donald Cha and Danny Gaeta
# Fall Semester 2015
# SEE README FILE FOR MORE INFO

#used to check pcap input
import sys 
import simplejson
import codecs

#used to silence unnecessary warnings
import logging
logging.getLogger("scapy.runtime").setLevel(logging.ERROR) 

#import scapy
from scapy.all import *

# Check to make sure user passed in a pcap file
if len(sys.argv) != 2:
    print("Usage: ./sniffy <pcap name>")
    print "For more info try: ./sniffy --help"
    exit()

if sys.argv[1] == "--help":
    print "############################################################"
    print "                    WElCOME TO SNIFFY"
    print "############################################################"
    print "#                                                          #"
    print "# Sniffy is a TCP packet sniffer and quite easy to use.    #"
    print "# Just activate sniffy and pass it the pcap file you       #"
    print "# would like to extract TCP packet information from        #"
    print "# Like this:                                               #"
    print "#                                                          #"
    print "#               ./sniffy mypcap.pcap                       #"
    print "#                                                          # "
    print "# Sniffy will extract all information available from all   #"
    print "# TCP packets inside of your pcap, including packet data   #"
    print "# if available and will write all of the data into a file  #"
    print "# named sniffy_output.txt in your current directory.       #"
    print "#                                                          # "
    print "############################################################"
    print " Sniffy was written and is maintained by Shane Rogers using"
    print " Python and the Scapy library 2014   shane@shanerogers.info   "
    print "############################################################"
    
    exit()

# Set pcap to the name of the file and open it
# Print to screen that pcap is being opened 

pcap = sys.argv[1]
print " "
print " Opening",
print sys.argv[1]
print " "
pkts = rdpcap(pcap)

# Read all packets from pcap file and filter out
# only those having to do with TCP

pkt_no = 0
#sys.stdout = open('sniffy_output.txt', 'w')
pcap_json = open('pcap.json', 'wr+')
pcap_test = open('test.json', 'w')
packets = []


#try:
for p in pkts:
    pkt_no += 1
    ## write summary and other info from packets to file
    if p.haslayer(IP):
        if p.haslayer(Raw):
            try:
                packets.append({"PcapID": pcap, "Load": "some data found", "PIN": pkt_no, "time": p.time, "src": p[IP].src, "dest": p[IP].dst, "protocol": p[IP].proto, "seq-window": p[IP].id, "length": p[IP].len})

            except:
                packets.append({"PcapID": pcap, "PIN": pkt_no, "time": p.time, "src": p[IP].src, "dest": p[IP].dst, "protocol": p[IP].proto, "seq-window": p[IP].id, "length": p[IP].len, "Load": "Invalid Data"})
        else:
            packets.append({"PcapID": pcap, "PIN": pkt_no, "time": p.time, "src": p[IP].src, "dest": p[IP].dst, "protocol": p[IP].proto, "seq-window": p[IP].id, "length": p[IP].len, "Load": "None"})  
    if p.haslayer(ARP):
        packets.append({"PcapID": pcap, "PIN": pkt_no, "time": p.time, "src": p[ARP].psrc, "dest": p[ARP].pdst, "protocol": "ARP", "seq-window": "None", "length": p[ARP].plen, "Load": "None"})

simplejson.dump(packets, pcap_json, sort_keys=True, indent=4, separators=(',', ': '))

reload = simplejson.load(pcap_json)
#print reload[0]
#print reload[1]
sys.stdout = sys.__stdout__
if pkt_no > 0:
    print " Packet info written to pcap.json"
    print " "
if pkt_no == 0:
    print " No Packet Traffic Found "
    print " "