#! /usr/bin/python
# SniffyDB is a CS 411 Project 
# by Shane Rogers, Simon Kim, Donald Cha and Danny Gaeta
# Fall Semester 2015
# SEE README FILE FOR MORE INFO

#used to check pcap input
import sys 
import json
import codecs

#used to silence unnecessary warnings
import logging
logging.getLogger("scapy.runtime").setLevel(logging.ERROR) 

#import scapy
from scapy.all import *

# Check to make sure user passed in a pcap file
if len(sys.argv) != 2:
    print("Usage: ./sniffy <pcap name>")
    print "For more info try: ./sniffy --help"
    exit()

if sys.argv[1] == "--help":
    print "############################################################"
    print "                    WElCOME TO SNIFFY"
    print "############################################################"
    print "#                                                          #"
    print "# Sniffy is a TCP packet sniffer and quite easy to use.    #"
    print "# Just activate sniffy and pass it the pcap file you       #"
    print "# would like to extract TCP packet information from        #"
    print "# Like this:                                               #"
    print "#                                                          #"
    print "#               ./sniffy mypcap.pcap                       #"
    print "#                                                          # "
    print "# Sniffy will extract all information available from all   #"
    print "# TCP packets inside of your pcap, including packet data   #"
    print "# if available and will write all of the data into a file  #"
    print "# named sniffy_output.txt in your current directory.       #"
    print "#                                                          # "
    print "############################################################"
    print " Sniffy was written and is maintained by Shane Rogers using"
    print " Python and the Scapy library 2014   shane@shanerogers.info   "
    print "############################################################"
    
    exit()

# Set pcap to the name of the file and open it
# Print to screen that pcap is being opened 

pcap = sys.argv[1]
print " "
print " Opening",
print sys.argv[1]
print " "
pkts = rdpcap(pcap)

# Read all packets from pcap file and filter out
# only those having to do with TCP

pkt_no = 0
#sys.stdout = open('sniffy_output.txt', 'w')
pcap_json = codecs.open('pcap.json', encoding='latin-1', mode='w+')
pcap_test = open('test.json', 'w')

#try:
for p in pkts:
    pkt_no += 1
    ## write summary and other info from packets to file
    if p.haslayer(IP):
        if p.haslayer(Raw):
            try:
                packet_info = {"Packet": {"PcapID": pcap, "PIN": pkt_no, "time": p.time, "src": p[IP].src, "dest": p[IP].dst, "protocol": p[IP].proto, "seq-window": p[IP].id, "length": p[IP].len, "Load": p[Raw].load}}
                json.dump(packet_info, pcap_test)
                json.dump(packet_info, pcap_json, sort_keys=True, indent=4, separators=(',', ': '))
                pcap_json.write(str(',\n'))
            except:
                packet_info = {"Packet": {"PcapID": pcap, "PIN": pkt_no, "time": p.time, "src": p[IP].src, "dest": p[IP].dst, "protocol": p[IP].proto, "seq-window": p[IP].id, "length": p[IP].len, "Load": "Invalid data"}}
                json.dump(packet_info, pcap_json, sort_keys=True, indent=4, separators=(',', ': '))
                pcap_json.write(str(',\n'))
        else:
            packet_info = {"Packet": {"PcapID": pcap, "PIN": pkt_no, "time": p.time, "src": p[IP].src, "dest": p[IP].dst, "protocol": p[IP].proto, "seq-window": p[IP].id, "length": p[IP].len, "Load": "None"}}        
            json.dump(packet_info, pcap_json, sort_keys=True, indent=4, separators=(',', ': '))
            pcap_json.write(str(',\n'))   
    if p.haslayer(ARP):
        packet_info = {"Packet": {"PcapID": pcap, "PIN": pkt_no, "time": p.time, "src": p[ARP].psrc, "dest": p[ARP].pdst, "protocol": "ARP", "seq-window": "None", "length": p[ARP].plen}}
        json.dump(packet_info, pcap_json, sort_keys=True, indent=4, separators=(',', ': '))            
        pcap_json.write(str(',\n'))
#except Exception as e:
#    print 'Error within packet: ' + str(pkt_no) + ' . The full error was: ' + str(e) 

sys.stdout = sys.__stdout__
if pkt_no > 0:
    print " Packet info written to pcap.json"
    print " "
if pkt_no == 0:
    print " No Packet Traffic Found "
    print " "